const numero = 10;
const numero2 = 20;
const numero3 = 30;

console.log(numero);

// Esto nos permite enterarnos del error pero aun asi continuar ejecutando el c√≥digo
try {
  console.log(numeros2);
} catch (error) {
  console.log(error);
}

console.log(numero3);
